# Generated by Django 5.0.1 on 2024-02-07 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users_table',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Customer', 'Customer'), ('Shopkeeper', 'Shopkeeper')], max_length=100)),
            ],
            options={
                'db_table': 'users_table',
            },
        ),
        migrations.CreateModel(
            name='shops_table',
            fields=[
                ('shopkeeper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usersApiApp.users_table')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'shops_table',
            },
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[('One', 1), ('Two', 2), ('Three', 3), ('Four', 4), ('Five', 5)])),
                ('comments', models.CharField(max_length=100)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='usersApiApp.users_table')),
                ('shopkeeper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper', to='usersApiApp.users_table')),
            ],
            options={
                'db_table': 'feedback_table',
            },
        ),
    ]
