# Generated by Django 5.0.1 on 2024-02-07 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_table',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='usersApiApp.users_table'),
        ),
        migrations.AlterField(
            model_name='feedback_table',
            name='shopkeeper_id',
            field=models.ForeignKey(db_column='shopkeeper_id', on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper', to='usersApiApp.users_table'),
        ),
        migrations.AlterField(
            model_name='shops_table',
            name='shopkeeper_id',
            field=models.ForeignKey(db_column='shopkeeper_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usersApiApp.users_table'),
        ),
    ]
