# Generated by Django 5.0.1 on 2024-02-07 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items_table',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'items_table',
            },
        ),
        migrations.CreateModel(
            name='orders_table',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.FloatField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=100)),
            ],
            options={
                'db_table': 'orders_table',
            },
        ),
        migrations.CreateModel(
            name='users_table',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Customer', 'Customer'), ('Shopkeeper', 'Shopkeeper')], max_length=100)),
            ],
            options={
                'db_table': 'users_table',
            },
        ),
        migrations.CreateModel(
            name='transactions_table',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('item_id', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='ordersApiApp.items_table')),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='ordersApiApp.orders_table')),
            ],
            options={
                'db_table': 'transactions_table',
            },
        ),
        migrations.AddField(
            model_name='orders_table',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='ordersApiApp.users_table'),
        ),
        migrations.AddField(
            model_name='orders_table',
            name='shopkeeper_id',
            field=models.ForeignKey(db_column='shopkeeper_id', on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper', to='ordersApiApp.users_table'),
        ),
    ]
