# Generated by Django 5.0.1 on 2024-02-07 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersApiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shops_table',
            fields=[
                ('shopkeeper_id', models.ForeignKey(db_column='shopkeeper_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ordersApiApp.users_table')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'shops_table',
            },
        ),
        migrations.AlterField(
            model_name='orders_table',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='ordersApiApp.users_table'),
        ),
        migrations.AlterField(
            model_name='orders_table',
            name='shopkeeper_id',
            field=models.ForeignKey(db_column='shopkeeper_id', on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper_orders', to='ordersApiApp.users_table'),
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[('One', 1), ('Two', 2), ('Three', 3), ('Four', 4), ('Five', 5)])),
                ('comments', models.CharField(max_length=100)),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='customer_feedback', to='ordersApiApp.users_table')),
                ('shopkeeper_id', models.ForeignKey(db_column='shopkeeper_id', on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper_feedback', to='ordersApiApp.users_table')),
            ],
            options={
                'db_table': 'feedback_table',
            },
        ),
        migrations.CreateModel(
            name='inventory_table',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('item_id', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='ordersApiApp.items_table')),
                ('shopkeeper_id', models.ForeignKey(db_column='shopkeeper_id', on_delete=django.db.models.deletion.CASCADE, to='ordersApiApp.users_table')),
            ],
            options={
                'db_table': 'inventory_table',
            },
        ),
    ]
