# Generated by Django 5.0.1 on 2024-02-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersApiApp', '0004_orders_table_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_table',
            name='completion_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
