# Generated by Django 5.0.1 on 2024-02-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersApiApp', '0006_alter_feedback_table_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_table',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
